### PR TITLE
tried out a first example

### PR DESCRIPTION
**Pull request by grewered**
So, I tried writing a very simple example, but it just creates a new empty column like this:
grafik
grafik

is the input from dat wrong? But it's not specified anywhere what kind of input the function needs. 
I looked at the function step by step to see what it does, and I have a few questions. 

-----
here it checks whether the labels are NA, right?
grafik

but i don't understand how they can be anything other than FALSE if these lines don't make it possible to be anything else, even if you specified something else in the function call:
grafik

it's a similar problem with label_est.
grafik
this line can't really work, if 1) dat$label_est is specified as "" earlier inside the function and 2) label_sig_bold is not mentioned as an argument in the info, even though its default is NULL. So under which circumstances is label_est going to be bold?

### CODE REVIEW

**Comment by grewered** [comment]
Also, how do I check for these the best? or can I just ignore that for now?

grafik

**Comment by grewered** [comment]
when I run this line of code, shouldn't there be a new column for label_sig_high?
grafik

-----------------

I know you managed to get something in the table bold, but when I look at the function, I don't see where the input is actually testet for significances. 

I only see this:
grafik

but that makes values only bold or in superscript when their value = TRUE or 1, not if it's significant. Am I wrong?

**Comment by grewered** [comment]
@nickhaf Can you look at my example to find out why it isn't in superscript?

**Comment by nickhaf** [comment]
So, I've looked into it and the problem seems to be, that the p-column needs to contain TRUE and FALSE values instead of numeric values. That's because this function was used within another function, which converted the p-values into TRUE and FALSE values before using `construct_label()`. 
So for now you can just use TRUE/FALSE values in your example instead of p-values. 
I will have to update the funciton a bit, so it can also take p-values, but I will open an Issue for that.

**Review by nickhaf — APPROVED** [review]
Looks great, thank you.

**Comment by grewered** [comment]
@nickhaf so shall I merge then?

**Comment by nickhaf** [comment]
> @nickhaf so shall I merge then?

Yes please!

**Pull request merged**
